# Generated by Django 5.2 on 2025-04-12 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.library'),
        ),
    ]
