# Generated by Django 5.2 on 2025-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_library_user_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
