# Generated by Django 5.2 on 2025-04-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_borrowrecord_is_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='fine_date',
            new_name='issued_date',
        ),
        migrations.AddField(
            model_name='fine',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fine',
            name='borrow_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='core.borrowrecord'),
        ),
    ]
