# Generated by Django 4.2.20 on 2025-04-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.library'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Sci-fi', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography'), ('History', 'History'), ('Children', 'Children'), ('Romance', 'Romance'), ('Selfhelp', 'Self-Help')], max_length=20, unique=True),
        ),
    ]
